// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: internal/doc/query.proto

package doc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word   string  `protobuf:"bytes,1,opt,name=Word,proto3" json:"Word,omitempty"`
	WordTF float32 `protobuf:"fixed32,2,opt,name=WordTF,proto3" json:"WordTF,omitempty"`
}

func (x *KeyWord) Reset() {
	*x = KeyWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_doc_doc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyWord) ProtoMessage() {}

func (x *KeyWord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_doc_doc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyWord.ProtoReflect.Descriptor instead.
func (*KeyWord) Descriptor() ([]byte, []int) {
	return file_internal_doc_doc_proto_rawDescGZIP(), []int{0}
}

func (x *KeyWord) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *KeyWord) GetWordTF() float32 {
	if x != nil {
		return x.WordTF
	}
	return 0
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Id       string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Keywords []*KeyWord        `protobuf:"bytes,2,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	Content  map[string]string `protobuf:"bytes,4,rep,name=Content,proto3" json:"Content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_doc_doc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_internal_doc_doc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_internal_doc_doc_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetKeywords() []*KeyWord {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Document) GetContent() map[string]string {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_internal_doc_doc_proto protoreflect.FileDescriptor

var file_internal_doc_doc_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x63, 0x2f, 0x64,
	0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x63, 0x22, 0x35, 0x0a,
	0x07, 0x4b, 0x65, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x57, 0x6f, 0x72, 0x64, 0x54, 0x46, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x57, 0x6f,
	0x72, 0x64, 0x54, 0x46, 0x22, 0xb6, 0x01, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x6f, 0x63, 0x2e, 0x4b, 0x65, 0x79, 0x57, 0x6f, 0x72,
	0x64, 0x52, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64,
	0x6f, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x63, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_doc_doc_proto_rawDescOnce sync.Once
	file_internal_doc_doc_proto_rawDescData = file_internal_doc_doc_proto_rawDesc
)

func file_internal_doc_doc_proto_rawDescGZIP() []byte {
	file_internal_doc_doc_proto_rawDescOnce.Do(func() {
		file_internal_doc_doc_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_doc_doc_proto_rawDescData)
	})
	return file_internal_doc_doc_proto_rawDescData
}

var file_internal_doc_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_doc_doc_proto_goTypes = []interface{}{
	(*KeyWord)(nil),  // 0: doc.KeyWord
	(*Document)(nil), // 1: doc.Document
	nil,              // 2: doc.Document.ContentEntry
}
var file_internal_doc_doc_proto_depIdxs = []int32{
	0, // 0: doc.Document.Keywords:type_name -> doc.KeyWord
	2, // 1: doc.Document.Content:type_name -> doc.Document.ContentEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_doc_doc_proto_init() }
func file_internal_doc_doc_proto_init() {
	if File_internal_doc_doc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_doc_doc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_doc_doc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_doc_doc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_doc_doc_proto_goTypes,
		DependencyIndexes: file_internal_doc_doc_proto_depIdxs,
		MessageInfos:      file_internal_doc_doc_proto_msgTypes,
	}.Build()
	File_internal_doc_doc_proto = out.File
	file_internal_doc_doc_proto_rawDesc = nil
	file_internal_doc_doc_proto_goTypes = nil
	file_internal_doc_doc_proto_depIdxs = nil
}
